name: OCI_Deploy

on:
  push:
    branches: [oci]
  workflow_dispatch:
    inputs:
      env:
        required: true
        type: string
        default: 'dev'
env:
  REPOSITORY: 'sdk-apps'
  IMAGE_TAG: ${{ github.event.repository.name }} 
        
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  
  
  
jobs:
  PushToOCI:
    runs-on: ubuntu-22.04
    name: Get OCIR Repository
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
    steps:
      - name: Get or create an OCIR Repository
        uses: oracle-actions/get-ocir-repository@v1.2.1
        id: get-ocir-repository
        with:
          name: sdk-apps
          compartment: ${{ secrets.OCI_COMPARTMENT_OCID }}

      - name: Log into OCIR
        uses: oracle-actions/login-ocir@v1.2.1
        id: login-ocir
        with:
          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}
      
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Tag and push a container image
        id: tag-and-push-image
        run: |
          docker build . -t "${{ steps.get-ocir-repository.outputs.repo_path }:$IMAGE_TAG"
          docker push "${{ steps.get-ocir-repository.outputs.repo_path }}:$IMAGE_TAG"  
  
